### ISSUE TITLE
Support App Privacy Manifests

### ISSUE THREAD

**Issue by imk1t** [zhangao0086/DKPhotoGallery#42]
## Issue Description
DKPhotoGallery was listed on the list of requirements for third-party SDKs announced by Apple.
Is there any push on DKPhotoGallery part to include Privacy Manifests files or sign the SDK?
https://developer.apple.com/support/third-party-SDK-requirements/

### What

If this is not addressed, apps containing DKPhotoGallery will not be able to be submitted to the AppStore beginning in the spring of 2024.

**Comment by percival888** [comment]
+1

**Comment by BaroneX** [comment]
When will it be updated?

**Comment by torycons** [comment]
+1

**Comment by romaCaldeira** [comment]
+1

**Comment by romaCaldeira** [comment]
+1

**Comment by arenrover0** [comment]
+1

**Comment by BaroneX** [comment]
Podfile.lock
```
DKImagePickerController/PhotoGallery (4.3.7):
    - DKImagePickerController/Core
    - DKPhotoGallery
```
If you have already included DKImagePickerController, there is no need to separately add DKPhotoGallery.

**Comment by navaronbracke** [comment]
@zhangao0086 I think the PrivacyManifest is missing the Required Reason for the FileTimestamp API.

You use it here https://github.com/zhangao0086/DKImagePickerController/blob/develop/Sources/DKImagePickerController/DKImageAssetExporter.swift#L353-L355 but the PrivacyManifest does not declare its use.

I think we need to declare reason `3B52.1` ? Since the `DKAsset` actually represents the photo or video that was picked by the user.
